name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:4.1
    steps:
      - uses: actions/checkout@v5
        with:
          path: config
      - name: Clone ZMK fork
        run: git clone --depth 5 -b go60-main https://github.com/mgabor3141/zmk.git /zmk
      - name: Initialize west workspace
        working-directory: /zmk
        run: west init -l app
      - name: Update modules
        working-directory: /zmk
        run: west update --fetch-opt=--filter=tree:0
      - name: Export Zephyr CMake package
        working-directory: /zmk
        run: west zephyr-export
      - name: Remove conflicting Zephyr cirque driver
        run: |
          rm -f /zmk/zephyr/dts/bindings/input/cirque,pinnacle-*.yaml
          rm -f /zmk/zephyr/drivers/input/input_pinnacle.c
          sed -i '/Kconfig.pinnacle/d' /zmk/zephyr/drivers/input/Kconfig
          sed -i '/input_pinnacle/d' /zmk/zephyr/drivers/input/CMakeLists.txt
      - name: Build LH
        working-directory: /zmk
        run: >
          west build -p -s app -b go60_lh -d /build/go60_lh --
          -DKEYMAP_FILE=$GITHUB_WORKSPACE/config/config/go60.keymap
          -DEXTRA_CONF_FILE=$GITHUB_WORKSPACE/config/config/go60.conf
      - name: Build RH
        working-directory: /zmk
        run: >
          west build -p -s app -b go60_rh -d /build/go60_rh --
          -DKEYMAP_FILE=$GITHUB_WORKSPACE/config/config/go60.keymap
          -DEXTRA_CONF_FILE=$GITHUB_WORKSPACE/config/config/go60.conf
      - name: Combine firmware
        run: cat /build/go60_lh/zephyr/zmk.uf2 /build/go60_rh/zephyr/zmk.uf2 > go60.uf2
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: go60.uf2
          path: go60.uf2
